### ISSUE TITLE
Trident Multishot breaks with Enchancement (?)

### ISSUE THREAD

**Issue by Comthefox2486** [OffsetMods538/Better-Multishot#15]
We got this mod because our _entire_ group is obsessed with Multishot. It works great! And most features of Enchancement work on the items too (We got a normal bow with Chaos and Multishot and shot 7 tipped arrows, it was a great time). But as the only one in my group that had/cared about tridents, I grabbed one with Multishot, and it did not change the amount thrown. Here's a [clip](https://youtu.be/9FHT7tCTzy4)

**Comment by OffsetMonkey538** [comment]
What other enchantments does the trident have?

**Comment by Comthefox2486** [comment]
> What other enchantments does the trident have?

That specific trident has a handful, but I got the same result with a clean multishot only Trident.

**Comment by OffsetMonkey538** [comment]
Could you send your mods list so I can test myself?

**Comment by Comthefox2486** [comment]
Hey! Sorry for the delay!![ Here's a link to the modpack I'm using. ](https://drive.google.com/file/d/12F-GYcjNFi36Zmu5akuVtqQq4mfZg6m_/view?usp=sharing)If there's anything I can do to help this issue I'll be more than happy to oblige.s

**Comment by OffsetMonkey538** [comment]
Hello! Thanks for the link, but it isn't working. It's telling me that the content was removed for breaking the terms of service.

**Comment by Comthefox2486** [comment]
Ouch x_x seems Google doesn't really enjoy Minecraft Mods. I'll request a review of it because none of the mods should be malicious.

**Comment by Comthefox2486** [comment]
If that is the case, here's the modlist MultiMC spits out when I boot the game
[Mod List.txt](https://github.com/OffsetMods538/Better-Multishot/files/14547279/Mod.List.txt)
I will try to look for all of the download links, but it will take a hot minute because it's kind of fragmented across the web.

**Comment by OffsetMonkey538** [comment]
Alright thank you! I can find the downloads myself. I will have a look at it in a bit

**Comment by OffsetMonkey538** [comment]
Found the mod that's the culprit #16

**Comment by Comthefox2486** [comment]
Thank you so much!

**Comment by OffsetMonkey538** [comment]
Working on fixing it

**Comment by OffsetMonkey538** [comment]
Alright this is something that I'm pretty sure requires changes from the other mod as well. I think I got something figured out so I sent them a PR, if it gets merged and a new version released, I can also fix it here
