### ISSUE TITLE
Multishot Trident Duplication

### ISSUE THREAD

**Issue by Ultimushadow** [OffsetMods538/Better-Multishot#6]
So uh, I was messing with the mod and saw you could put Multishot on a trident. If you also happen to put Loyalty on the trident, it ends up duplicating the return item by applying the Loyalty effect to all tridents. While hilarious, this may bring up some balance issues...

**Comment by Ultimushadow** [comment]
Oh, I found this so funny I forgot to ya know, give details
I can confirm this is occurring with version 2.3.1 of this mod on Fabric 0.14.21/0.14.22 in 1.20.1

**Comment by OffsetMonkey538** [comment]
Alright, I'm currently just updating the project to use what my new template uses and then I'll get to actually fixing the issue.

I guess one solution could be to just to not allow loyalty with multishot, but that's no fun! I could also just set the pickup type of those to creative only, but then they would just stay there like when you have a full inventory. I hope there's an easy way to just make it give nothing, but if there isn't then I can probably just mixin to create a new variable for the thrown trident and only make it drop an item when that is false or something.


Wow it took me 7 minutes to write that lol

**Comment by Ultimushadow** [comment]
I'm not familiar with the trident coding so I'm just guessing here, would it be easier to selectively apply loyalty to only one of the projectiles and allow the others to remain in the ground like it is when you don't have loyalty? Obviously this would have to be a hard coded exception to the normal rules of the mod, or.. at least I think that's what you would have to do to accomplish this since you'd be checking for loyalty specifically

**Comment by OffsetMonkey538** [comment]
That seems like an idea. I honestly don't remember anymore if I made it so I have access to the multishot projectiles in the projectile mixin itself lol. I'll check in a minute, still updating everything.

**Comment by Ultimushadow** [comment]
Ah yeah, that would have to be done carefully to avoid conflicts, didn't think of that.
No rush from me! Just like to brainstorm lol

**Comment by OffsetMonkey538** [comment]
> No rush from me!

Well: Yes rush from me

**Comment by OffsetMonkey538** [comment]
Made it so the loyalty wouldn't be applied to the multishot projectiles. Could you test the artifact from [here](https://github.com/OffsetMods538/Better-Multishot/actions/runs/5963720012)? Just download the `Artifacts` archive and put the one that doesn't have `-ANYTHING` after it in your mods folder.

**Comment by Ultimushadow** [comment]
Will do later tonight, had a busy day today!

**Comment by Ultimushadow** [comment]
Ha, and here I was just about to say I think we're good! I tested it and it works both creative and survival, drowned who pick up a trident with multishot don't have the effect applied (which would be terrifying), but I felt like something was not right so I ended up reloading the world to double check. Well, upon reloading the world, all the multishot tridents in the ground had the Loyalty effect put on them immediately and they all went back into my inventory! This seems to work in both creative and survival, but in creative the item no longer pops into the inventory. On survival, different story, a couple shots and my whole inventory was full on relog

**Comment by OffsetMonkey538** [comment]
Hmm, I think I might know what's happening

**Comment by Ultimushadow** [comment]
Is the dealt damage nbt value getting reset when reloaded? Then once it hits 1 again, it checks for the enchants and finds loyalty? I wonder if I can use carpet to freeze the game and verify that's what's going on

**Comment by OffsetMonkey538** [comment]
Nah I think I got it. I just modified the LOYALTY data if the trident was from multishot, but it still saved the ItemStack with the loyalt enchantment as NBT so when it reloaded the world, it loaded the tridents from that stack and got loyalty

**Comment by Ultimushadow** [comment]
Ah okay, I had noticed the item stack was still in nbt but wasn't sure if that was intentionally left in

**Comment by OffsetMonkey538** [comment]
Alright, you can try the artifacts from [here](https://github.com/OffsetMods538/Better-Multishot/actions/runs/5975683848) once it finishes building.

**Comment by Ultimushadow** [comment]
Alright that bug appears to be squashed, I tested with tridents already in the ground and midair just in case, with the enchantment no longer in nbt nothing wants to come back regardless of the circumstances
I can't think of any other way this would be able to result in duplication so that's that! I'll be putting this into a decent sized pack so I'll let you know if anything conflicts there in the future

**Comment by Ultimushadow** [comment]
Thank you for the quick turn around! I am looking forwards to turning my trident into a shotgun lmao

**Comment by OffsetMonkey538** [comment]
Oh nice, I'll merge this into master and upload to modrinth then.
I also have some other Better enchantment mods, so make sure to check those out too or something idk #ad

**Comment by Ultimushadow** [comment]
I actually have your Frost Walker mod in my pack already! I didn't see the Fire Aspect one, that looks handy and I'll probably try to get that in, I have a handful of enchantments going in the pack at the moment, will probably pop up in a thread on that repository soon 😅
